// Generated by LiveScript 1.3.1
(function(){
  this.createGame = function(gameNumber, size, length){
    switch (gameNumber) {
    case 0:
      return new TicTacToeGame(size, 'O', 'X', length);
    case 1:
      return new FillRowGame(size);
    }
  };
  this.createGameFromParams = function(){
    document.getElementById('lineLengthDiv').style.display = +!document.getElementById('gameName').selectedIndex ? 'block' : 'none';
    if (window.game != null) {
      if (window.game.field != null) {
        window.game.field.destructor();
      }
    }
    return window.game = createGame(document.getElementById('gameName').selectedIndex, +document.getElementById('size').value, +document.getElementById('length').value);
  };
  window.onload = createGameFromParams;
}).call(this);
