// Generated by LiveScript 1.3.1
(function(){
  this.game = function(){
    var size, data, currentPlayer, startPos, playerElement, stateElement, selectCell, fillCells, checkGameOver, isGameOver, nextTurn;
    size = +document.getElementById('size').value || 4;
    data = repeatArray$(repeatArray$([0], size), size);
    currentPlayer = 2;
    startPos = null;
    playerElement = document.getElementById('player');
    stateElement = document.getElementById('state');
    selectCell = function(){
      if (+this.innerText) {
        return alert("Эту клетку нельзя выбрать");
      }
      if (startPos != null) {
        fillCells(startPos, +this.id);
        return checkGameOver();
      } else {
        startPos = +this.id;
        return stateElement.innerText = "Выберите конечную клетку";
      }
    };
    fillCells = function(startPos, endPos){
      var isColumn, i$, j, element, results$ = [];
      if (startPos > endPos) {
        startPos = [endPos, endPos = startPos][0];
      }
      isColumn = endPos - startPos >= size;
      if (isColumn && (endPos - startPos) % size) {
        return alert("Выберите конечную клетку на одной горизонталиили вертикали с текущей клеткой");
      }
      for (i$ = startPos; i$ <= endPos; ++i$) {
        j = i$;
        if ((j % size === endPos % size && isColumn) || !isColumn) {
          data[j] = 1;
          element = document.getElementById(j);
          element.innerText = 1;
          results$.push(element.className = 'touched');
        }
      }
      return results$;
    };
    checkGameOver = function(){
      if (isGameOver()) {
        alert("Победа за игроком номер " + currentPlayer);
        return game();
      } else {
        return nextTurn();
      }
    };
    isGameOver = function(){
      return !data.filter(function(a){
        return a === 0;
      }).length;
    };
    nextTurn = function(){
      currentPlayer = currentPlayer === 1 ? 2 : 1;
      playerElement.innerText = "Ход " + currentPlayer + " игрока";
      stateElement.innerText = "Выберите начальную клетку";
      return startPos = null;
    };
    (function(){
      var table, j, prevElement, element, results$ = [];
      if (document.getElementsByTagName("table").length) {
        document.body.removeChild(document.getElementsByTagName("table")[0]);
      }
      table = document.body.appendChild(document.createElement('table'));
      for (j in data) {
        if (!(j % size)) {
          table.appendChild(prevElement = document.createElement('tr'));
        }
        element = document.createElement('td');
        element.id = j;
        element.onclick = selectCell;
        element.innerText = 0;
        results$.push(prevElement.appendChild(element));
      }
      return results$;
    })();
    return nextTurn();
  };
  window.onload = game;
  function repeatArray$(arr, n){
    for (var r = []; n > 0; (n >>= 1) && (arr = arr.concat(arr)))
      if (n & 1) r.push.apply(r, arr);
    return r;
  }
}).call(this);
